let mySet= new Set();
mySet.add(2).add(4).add(5).add(2);
console.log(mySet);
let yourSet= new Set([2,3,5,2,8]);
//yourSet.clear();
yourSet.delete(2);
yourSet.delete(3);
console.log(yourSet);
console.log(mySet.has(5));
console.log(mySet.values());
console.log(yourSet.size);
